/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : Workspace Services
 #	author : miyako
 #	12/07/07
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include "functions_wksp.h"

void PluginMain(int32_t selector, PA_PluginParameters params)
{
	try
	{
		int32_t pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (int32_t pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
		case kDeinitPlugin :
			FULL_SCREEN_END();
			break;            
// --- Finder

		case 1 :
			FINDER_Perform_operation(pResult, pParams);
			break;

		case 2 :
			FINDER_Get_icon_for_file_type(pResult, pParams);
			break;

// --- Application

		case 3 :
			APPLICATION_Get_path(pResult, pParams);
			break;

		case 4 :
			APPLICATION_Launch(pResult, pParams);
			break;

		case 5 :
			APPLICATION_Launch_paths(pResult, pParams);
			break;

// --- File

		case 6 :
			FILE_Get_localized_name(pResult, pParams);
			break;

		case 7 :
			FILE_Open_with_application(pResult, pParams);
			break;

		case 8 :
			FILE_Get_application_name(pResult, pParams);
			break;

		case 9 :
			FILE_SET_ICON(pResult, pParams);
			break;

		case 10 :
			FILE_Get_icon(pResult, pParams);
			break;

// --- Dock

		case 11 :
			DOCK_SET_BADGE_LABEL(pResult, pParams);
			break;

		case 12 :
			DOCK_Get_icon(pResult, pParams);
			break;

		case 13 :
			DOCK_Get_badge_label(pResult, pParams);
			break;

		case 14 :
			DOCK_SET_ICON(pResult, pParams);
			break;

// --- Full Screen (QuickTime)

		case 15 :
			FULL_SCREEN_BEGIN(pResult, pParams);
			break;

		case 16 :
			FULL_SCREEN_END();
			break;

// --- Folder

		case 17 :
			FOLDER_GET_CONTENTS(pResult, pParams);
			break;

		case 18 :
			FOLDER_GET_SUBPATHS(pResult, pParams);
			break;

	}
}

